In [1]:
import pandas as pd

In [2]:
signal_df = pd.read_csv('digital.csv')

In [5]:
signal_df

,Time [s],Channel 1,Channel 2,Channel 3,Channel 4,Channel 5,Channel 6,Channel 7
0,0.000000,1,1,1,0,0,0,0
1,6.610810,1,1,1,1,0,0,0
2,6.610810,1,1,0,0,0,0,0
3,6.610850,1,1,0,0,0,0,1
4,6.610850,1,1,0,0,0,1,1
...,...,...,...,...,...,...,...,...
642,53.484560,0,1,1,1,1,1,0
643,53.484665,1,1,1,1,1,1,0
644,54.008447,1,1,1,0,0,0,1
645,54.008447,1,1,1,0,0,0,0
646,58.554169,1,1,1,0,0,0,0

In [6]:
filter_1 = (signal_df['Channel 1']==1) & (signal_df['Channel 2']==1) & (signal_df['Channel 3']==1) & (signal_df['Channel 4']==0) & (signal_df['Channel 5']==0) & (signal_df['Channel 6']==0) & (signal_df['Channel 7']==0)

In [10]:
signal_df[~filter_1].head(20)

,Time [s],Channel 1,Channel 2,Channel 3,Channel 4,Channel 5,Channel 6,Channel 7
1,6.610810,1,1,1,1,0,0,0
2,6.610810,1,1,0,0,0,0,0
3,6.610850,1,1,0,0,0,0,1
4,6.610850,1,1,0,0,0,1,1
5,6.610850,1,1,0,0,1,1,1
6,6.610850,1,1,1,1,1,1,1
7,6.610851,1,1,1,0,1,1,1
8,6.610851,1,1,0,0,1,1,1
9,6.735903,1,1,1,0,1,1,1
10,6.755965,1,1,1,0,1,1,0
11,6.755965,1,1,1,0,1,0,0
13,7.071915,1,1,0,0,0,0,0
14,7.071920,1,1,0,0,0,0,1
15,7.071920,1,1,0,0,0,1,1
16,7.071920,1,1,0,0,1,1,1
17,7.071920,1,1,1,1,1,1,1
18,7.071921,1,1,0,0,1,1,1
19,7.195707,1,1,1,0,1,1,1
20,7.215769,1,1,1,0,1,1,0
21,7.215769,1,1,1,0,1,0,0

In [11]:
keys = {'1,4':'1',
 '2,4':'2',
 '3,4':'3',
 '1,5':'4',
 '2,5':'5',
 '3,5':'6',
 '1,6':'7',
 '2,6':'8',
 '3,6':'9',
 '1,7':'*',
 '2,7':'0',
 '3,7':'#'}

In [35]:
seq =  '1,7L 2,4 3,5 2,6 1,5 1,4 2,5 3,6 2,7D 1,6T 2,5 3,4 1,4 3,4 3,6 1,6D 2,4 3,5 1,4T 2,6D 1,4 2,4 2,5 3,5 1,6D 2,6D 3,4 3,5L 3,6 2,5 2,6 2,7 1,4 1,7L'

In [36]:
teclas = seq.split(' ')

In [40]:
text = [keys[tecla[0:3]] + tecla[3] if len(tecla)>3 else keys[tecla[0:3]] for tecla in teclas]

In [41]:
text

['*L',
 '2',
 '6',
 '8',
 '4',
 '1',
 '5',
 '9',
 '0D',
 '7T',
 '5',
 '3',
 '1',
 '3',
 '9',
 '7D',
 '2',
 '6',
 '1T',
 '8D',
 '1',
 '2',
 '5',
 '6',
 '7D',
 '8D',
 '3',
 '6L',
 '9',
 '5',
 '8',
 '0',
 '1',
 '*L']

In [42]:
k2 = {
 '1':'1',
 '2':'2',
 '3':'3',
 '4':'4',
 '5':'5',
 '6':'6',
 '7':'7',
 '8':'8',
 '9':'9',
 '0':'0'
}

In [34]:
''.join([te[0] if '*' in te else k2[te] for te in text])

'33355524*26841590753139726181256783695801*'

In [43]:
len("a8QyqXx8vq4sHktxHfKgWmneA0rq_8GlRJvTxhkCs5g")

43